name: FTEQW Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  generate_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: actionquake/q2pro
          ref: ${{ github.ref }}

      - name: version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
        id: version
        
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: fteqw_${{ steps.version.outputs.short_sha }}
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Download web build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: make-web
          skip_unpack: true

      - name: Download Linux x64 build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: make-linux64
          skip_unpack: true

      - name: Download Win x64 build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: make-win64
          skip_unpack: true

      - name: Download Win x86 build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: make-win32
          skip_unpack: true 

      - name: Download Darwin arm64 build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: make-macos-arm64
          skip_unpack: true

      - name: Rename files for release
        run: |
          mv make-linux64.zip fteqw-linux64.zip
          mv make-win64.zip fteqw-win64.zip
          mv make-win32.zip fteqw-win32.zip
          mv make-macos-arm64.zip fteqw-macos-arm64.zip
          mv make-web.zip fteqw-web.zip


      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{ steps.version.outputs.version }}
          files: |
            fteqw-linux64.zip
            fteqw-macos-arm64.zip
            fteqw-web.zip
            fteqw-win32.zip
            fteqw-win64.zip

